services:
    # n8n workflow automation platform
    wkflowserv:
        build:
           context: ../shared/n8n/
        depends_on:
            wkflowinit:
                condition: service_completed_successfully
        environment:
            - N8N_PORT=5678
            - N8N_RUNNERS_ENABLED=true
            - N8N_HOST=workflow.${DOMAIN_NAME}
            - NODE_ENV=production
            - WEBHOOK_URL=https://${WKFLOW_DOMAIN}/
            - TZ=${TIME_ZONE}
            - GENERIC_TIMEZONE=${TIME_ZONE}
        image: wkflowserv
        labels:
            # Enable Traefik for this container
            - "traefik.enable=true"
            # Use the 'websecure' (HTTPS) entry point
            - "traefik.http.routers.wkflowserv.entrypoints=websecure"
            # Match incoming requests on a specific hostname
            - "traefik.http.routers.wkflowserv.rule=Host(`${WKFLOW_DOMAIN}`)"
            # Assign the router to a named Traefik service
            - "traefik.http.routers.wkflowserv.service=wkflowserv"
            # Define the internal container port for routing
            - "traefik.http.services.wkflowserv.loadbalancer.server.port=5678"
            # Enable TLS on this router
            - "traefik.http.routers.wkflowserv.tls=true"
            # uncomment when Domain Level Forward Authentication enabled in Authentik
            - "traefik.http.routers.wkflowserv.middlewares=middlewares-authentik@file"
            # Use Let's Encrypt for certificate management or Self-signed certificate
            - "traefik.http.routers.wkflowserv.tls.certresolver=letsencrypt"
        networks:
            - subnet
        ports:
            - 8050:5678
        restart: unless-stopped
        volumes:
            - ${APPS_DATA}/workflow/n8n:/home/node/.n8n

    # n8n workflow initial: fix volume permission
    wkflowinit:
        build:
            context: ../shared/busybox/
        command: ["sh", "-c", "chown -R 1000:1000 /home/node/.n8n"]
        image: wkflowinit
        networks:
            - subnet
        volumes:
            - ${APPS_DATA}/workflow/n8n:/home/node/.n8n

    # Qdrant Vector Database
    wkqdrantdb:
        build:
            context: ../shared/qdrant
        image: wkqdrantdb
        networks:
            - subnet
        ports:
            - 8051:6333
        restart: unless-stopped
        volumes:
            - ${APPS_DATA}/workflow/wkqdrantdb:/qdrant/storage

    wkflowreds:
        build:
            context: ../shared/redis
        command: --save 60 1 --loglevel warning
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            start_period: 20s
            interval: 30s
            retries: 5
            timeout: 3s
        image: authenreds
        networks:
            - subnet
        restart: unless-stopped
        volumes:
            - ${APPS_DATA}/workflow/wkflowreds:/data